# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171202_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='autor',
        ),
    ]
